#Operações bitwise

print("Parte 1 - Sistemas de base numérica")
input()

print("Sistema decimal = O nosso sistema, Base 10")
input()

print("Sistema binário = Base 2")
print("1001 = 1 * 2**3 + 0 * 2**2 + 0 * 2**1 + 1 * 2**0 = 8 + 0 + 0 + 1 = 9")
input()

print("Sistema Hexadecimal = Base 16")
print("0 1 2 3 4 5 6 7 8 9  a  b  c  d  e  f")
print("0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15")
print("4ef = 4 * 16**2 + 14 * 16**1 + 15 * 16**0 = 1263")
input()

print("Sistema Octal = Base 8")
print("217 = 2 * 8**2 + 1 * 8**1 + 7 * 8**0 = 143")
input()

print("Python lida bem com todos esses sistemas")
print("Temos até funções pré-definidas em python para")
print("lidar com isso")
input()

print("Função bin()")
print("Converte um número inteiro em número binário")
print("9 =", bin(9))
print("Note a string devolvida, existe um '0b' antes")
print("do ínicio do número, acontece que em python")
print("existe uma notação para trabalhar com o objeto")
print(type(bin(9)))
print("que representa o número binário")
input()

print("Podemos fazer a volta do bin para inteiro")
print("0b1001 =", int("0b1001", 2))
print("O segundo argumento do int indica a base do sistema")
print("em que estamos trabalhando, que no caso é 2.")
input()

print("Da mesma forma podemos converter um número")
print("inteiro para o formato de hex por meio da ")
print("função hex")
print("1263 =", hex(1263))
input()

print("Note que no caso do hex temos a denotação")
print("'0x' que indica que se trata de um número")
print("na base hexadecimal")
input()

print("Podemos fazer a volta do número hex para int")
print("da mesma forma que para o número binário, porém")
print("passando 16 como segundo argumento da função int")
print("0x4ef =", int("0x4ef", 16))
input()

print("Podemos fazer a mesma coisa para a base")
print("octal")
print("143 =", oct(143))
print("0o217 =", int("0o217", 8))
input()

print("Parte 2 - Operações Bitwise")
input()

print("Shift Left - Move a parte representativa do número um determinado valor para esquerda")
print("Exemplo: 0b000001 << 2 ou 1 << 2 ==> 0b000100 = 4")
print(0b000001 << 2, 1 << 2)
input()

print("Shift Right - Move a parte representativa do número um determinado valor para direita")
print("Exemplo: 0b0010100 >> 3 ou 20 >> 3 ==> 0b0000010 = 2")
print(0b0010100 >> 3, 20 >> 3)
input()

print("Bit AND = &")
print("Lembre-se que o número 1 = True e 0 = False, então se fizemos")
print("as seguintes operações, teríamos")
print("1 and 1 =", 1 and 1)
print("1 and 0 =", 1 and 0)
print("0 and 1 =", 0 and 1)
print("0 and 0 =", 0 and 0)
input()

print("Quando fazemos o operador bit AND entre dois números")
print("nós pegamos a representação binária desses números e realizamos")
print("a operação de AND para cada bit que representa os números")
print("Exemplo:	")
print("a:       00101010   42")
print("b:       00001111   15")
print("======================")
input()
print("a & b:   00001010   10")
print(0b00101010 & 0b00001111, 42 & 15)
input()

print("Bit OR = |")
print("Lembre-se que o número 1 = True e 0 = False, então se fizemos")
print("as seguintes operações, teríamos")
print("1 or 1 =", 1 or 1)
print("1 or 0 =", 1 or 0)
print("0 or 1 =", 0 or 1)
print("0 or 0 =", 0 or 0)
input()

print("Quando fazemos o operador bit OR entre dois números")
print("nós pegamos a representação binária desses números e realizamos")
print("a operação de OR para cada bit que representa os números")
print("Exemplo:	")
print("a:       00101010   42")
print("b:       00001111   15")
print("======================")
input()
print("a | b:   00101111   47")
print(0b00101010 | 0b00001111, 42 | 15)
input()

print("Bit XOR = ^ = exclusive or")
print("Neste caso as operações são um pouco mais complicadas")
print("Nós somamos os dois bit (soma normal 1+0 = 1, 1+1 = 2)")
print("E tiramos o resto da divisão por 2 para obter o bit")
print("do novo número, teríamos as seguintes respostas para")
print("as seguintes operações")
print("1 or 1 =", (1+1)%2)
print("1 or 0 =", (1+0)%2)
print("0 or 1 =", (0+1)%2)
print("0 or 0 =", (0+0)%2)
input()

print("Quando fazemos o operador bit XOR entre dois números")
print("nós pegamos a representação binária desses números e realizamos")
print("a operação de XOR para cada bit que representa os números")
print("Exemplo:	")
print("a:       00101010   42")
print("b:       00001111   15")
print("======================")
input()
print("a ^ b:   00100101   37")
print(0b00101010 ^ 0b00001111, 42 ^ 15)
input()

print("A operação XOR é de longe a mais importante, principalmente")
print("em criptografia por ser a única totalmente reversível")
input()

print("Exercício Fácil (Code Academy): ")
print("http://www.codecademy.com/pt/courses/python-intermediate-en-KE1UJ/2/1?curriculum_id=4f89dab3d788890003000096")
input()
